src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 */
class Property
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="integer")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default":false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="string")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = date("d-m-Y | H:i:s");
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postal_code;
    }

    public function setPostalCode(int $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function setCreatedAt(String $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

templates/pages/bien_details.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{properties.title}}
{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="row">
        <div class="col-8">
        </div>
        <div class="col4">
            <h1 class="text-center">{{properties.title}}</h1>
            <h2>{{properties.rooms}} pièces - {{properties.surface}} m²</h2>
            <div>{{properties.price | number_format('0','',' ')}}</div>
            <a href="#" class="btn btn-primary">Contacter l'agence</a>
        </div>
    </div>
    </div>
    <div class="container mt-4">
    
       <p>{{properties.description | nl2br }}</p>
        <div class="row">
            <div class="col-8">
                <table class="table table-striped">
                    <h2>Caractéristiques</h2>
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{properties.surface}} m²</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{properties.rooms}}</td>
                    </tr>
                    <tr>
                        <td>Nombre de chambre</td>
                        <td>{{properties.bedrooms}}</td>
                    </tr>
                    <tr>
                        <td>Étage</td>
                        <td>properties.floor</td>
                    </tr> 
                    <tr>
                        <td>Type de chauffage</td>
                        <td>{{properties.heat}}</td>
                    </tr> 
                </table>
            </div>
        </div>
        <div class="col-4">
            <h2>Spécificités</h2>
        </div>
    </div>
{% endblock %}

templates/pages/biens.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    Nos Biens
    {% endblock %}
{% block body %}
    <div class="container">
        <h1 class="text-center underline">Les biens</h1>
    </div>
{% endblock %}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
   
{% endblock %}

    {% block title %}
        Imo Express
    {% endblock %}
 {% block body %}
 <div class="body">
    <h1 class="text-center">Binevenu sur Imo Express, vous loger est notre priorité</h1>
    <div class="container jumbotron text-center">
        <h2 class="text-center">Nos dernières offres</h2>
            <div class="row">
                {% for bien in biens %}
                <div class="col-3">
                    <div class="card">
                        <div class="card card-head">
                            <a href="{{path('show',{'id': bien.id})}}">
                                <h5 class="card-title">{{bien.title}} </h5>
                            </a>
                                
                                <div class="card-body">
                                    <p>{{bien.city}} ({{bien.postalCode}})</p>
                                    <div class="text-danger">
                                        {{bien.price | number_format(0,'',' ')}} €
                                    </div>
                                </div>
                            
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
    </div>
</div>
 
 {% endblock %}